global:
  imagePullPolicy: Always

frontend:
  replicas: 1
  revisionHistoryLimit: 15
  strategy:
    type: Recreate
  service:
    port: 80
  ingress:
    host: front-aleksandr-smirnov.2sem.students-projects.ru
    path: /
    pathType: Prefix
    tls:
      enabled: true
      secretName: 2sem-students-projects-wildcard-secret
  containerPort: 80
  image: crocksgift/sausage-store-frontend:latest
  resources:
    requests:
      memory: "96Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  nginxConf: nginx.conf

backend:
  annotations:
    path: /actuator/prometheus
    port: "8080"
    scrape: "true"
  env:
    postgresUri: jdbc:postgresql://postgresql:5432/sausage-store
    postgresUser: store
    postgresPassword: storepassword
    reportPath: /logs/reports
    logPath: /logs
  service:
    port: 8080
  revisionHistoryLimit: 15
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  image: crocksgift/sausage-store-backend:latest
  imagePullPolicy: Always
  resources:
    requests:
      memory: "384Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  containerPort: 8080
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  vpa:
    enabled: true
    updatePolicy:
      updateMode: "Off"
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          controlledResources: ["cpu", "memory"]

backend-report:
  replicas: 1
  strategy:
    type: Recreate
  image: crocksgift/sausage-store-backend-report:latest
  imagePullPolicy: Always
  containerPort: 3000
  configMap:
    port: "3000"
  secret:
    mongodbUri: mongodb://reports:reportspassword@mongodb:27017/sausage-store
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75
  resources:
    requests:
      memory: "96Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

infra:
  postgresql:
    enabled: true
    postgresUser: store
    postgresPassword: storepassword
    postgresDb: sausage-store
    containerPort: 5432
    storage:
      size: 1Gi
    resources:
      requests:
        memory: "96Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  mongodb:
    env:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    containerPort: 27017
    resources:
      requests:
        memory: "96Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"

# Helm release history limit
historyMax: 3
