apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  annotations:
    helm.sh/hook-weight: "-5"
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-conf
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongodb-conf
              key: MONGO_INITDB_ROOT_PASSWORD
        ports:
        - containerPort: {{ .Values.mongodb.containerPort }}
        resources:
          {{- toYaml .Values.mongodb.resources | nindent 12 }}
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
        - name: mongodb-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: {{ .Values.mongodb.containerPort }}
    targetPort: {{ .Values.mongodb.containerPort }}
  selector:
    app: mongodb
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-conf
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.env.MONGO_INITDB_ROOT_PASSWORD }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mongodb-init
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: mongodb-init
        image: mongo:7.0
        command:
        - mongosh
        - "mongodb://root:rootpassword@mongodb:27017/admin"
        - --eval
        - |
          db = db.getSiblingDB("sausage-store");
          try {
            db.dropUser("reports");
          } catch (err) {
            print("User reports does not exist yet, continuing...");
          }
          db.createUser({
            user: "reports",
            pwd: "reportspassword",
            roles: [
              { role: "readWrite", db: "sausage-store" }
            ]
          });
          print("User reports created successfully!");
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: mongodb-conf
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: mongodb-conf
              key: MONGO_INITDB_ROOT_PASSWORD
        resources:
          {{- toYaml .Values.mongodbInit.resources | nindent 12 }}
      restartPolicy: OnFailure
