apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-report
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: {{ .Values.strategy.type }}
  selector:
    matchLabels:
      app: backend-report
  template:
    metadata:
      labels:
        app: backend-report
    spec:
      containers:
        - name: backend-report
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: backend-report-config
            - secretRef:
                name: backend-report-secret
          volumeMounts:
            - name: env-config
              mountPath: /app/.env
              subPath: .env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: env-config
          configMap:
            name: backend-report-env
