apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-report-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-report
  minReplicas: {{ .Values.backend-report.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend-report.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend-report.hpa.targetCPUUtilizationPercentage }}
