apiVersion: v1
kind: Service
metadata:
  name: backend-report
spec:
  selector:
    app: backend-report
  ports:
    - protocol: TCP
      port: {{ .Values.backend-report.containerPort }}
      targetPort: {{ .Values.backend-report.containerPort }}
