apiVersion: v1
kind: Service
metadata:
  name: backend-report
spec:
  selector:
    app: backend-report
  ports:
    - protocol: TCP
      port: {{ index .Values "backend-report" "containerPort" }}
      targetPort: {{ index .Values "backend-report" "containerPort" }}
