apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: backend-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       backend
  updatePolicy:
    updateMode: {{ .Values.backend.vpa.updatePolicy.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
      {{- toYaml .Values.backend.vpa.resourcePolicy.containerPolicies | nindent 6 }}
